# Generated by Django 4.0.6 on 2022-07-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=100, null=True)),
            ],
        ),
    ]
